[package]
name = "national_debt"
version = "0.0.0"
edition = "2021"


[dependencies]
common = { path = "../common" }

serde = { version = "1.0.214", features = ["rc"] }
serde_json = { version = "1.0.132", features = ["preserve_order"] }
