[package]
name = "alrightguysnewprojecttime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.147"
serde_json = "1.0.87"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "voice", "cache", "collector"] }
tokio = { version = "1.13.0", features = ["full"] }
ytd-rs = { version = "0.1.0", features = ["yt-dlp"] }
nanoid = "0.4.0"
poll-promise = { version = "0.2.0", features = ["tokio"] }
tracing = "0.1.23"
tracing-subscriber = "0.3.16"
dirs = "4.0.0"
anyhow = "1.0.66"
audiotags = "0.4.1"
songbird = {version = "0.3.0", features = ["yt-dlp", ]}
# url = "2.3.1"
reqwest = "0.11.12"
# html = "0.1.1"
rand = "0.8.5"
# rayon = "1.5.3"
ffprobe = "0.3.3"
base64 = "0.13.1"
powershell_script = "1.0.4"


# [profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"

[features]
default = ["download"]
download = []