[workspace]
members = [
    "neon_circle",
    "voice_events",
    "common",
    "config-command",
    "music-commands",
    "lts",
    "national-debt",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
