[package]
name = "config_command"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
long_term_storage = { path = "../lts" }
serde = { version = "1.0.214", features = ["rc"] }
serde_json = { version = "1.0.132", features = ["preserve_order"] }
