[package]
name = "long_term_storage"
version = "0.0.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = [
    "postgres",
    "runtime-tokio",
    "chrono",
    "uuid",
] }
common = { path = "../common" }
